name: Build & deploy Spring Boot app

on:
  push:
    branches:
      - master

jobs:
  builds-deploy:
    name: Build and deploy Spring boot (CI/CD and K8s)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17 JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Unit tests
        run: ./gradlew test

      - name: Build the application
        run: |
          ./gradlew clean build