name: Build & deploy Spring Boot app

on:
  push:
    - master
  pull_request:
    branches:
      - master

jobs:
  builds-deploy:
    name: Build and deploy Spring boot (CI/CD and K8s)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17 JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew test

      - name: Push image
        run: | 
          docker login --username pedroalmeida96 --password ${{ secrets.GHCR_ACCESS_TOKEN }} ghcr.io
          docker build . --tag ghcr.io/pedroalmeida96/cicd-k8s:latest
          docker push ghcr.io/pedroalmeida96/cicd-k8s:latest